spring:
  datasource:
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USERNAME_DEV}
    password: ${DATABASE_PASSWORD_DEV}
  liquibase:
    change-log: classpath:db/master.yml

  jpa:
    show-sql: true